name: Pytest

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
        pip install pytest
        pip install pytest-cov
        pip install coverage
        python3 -m pip install --user dist/*.whl

    - name: Run pytest
      run: make test
    - name: Run coverage
      run: make test-coverage
