name: Test_coverage

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install pytest
          pip install pyyaml
          pip install coverage
          pip install pytest-cov
          poetry add pytest
          poetry add pyyaml
          poetry add coverage
          poetry add pytest-cov
          make install

      - name: Run Tests
        run: |
          make test
      
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
